# Basic
title: 学习资料
subtitle: 20级某大学某学院的学习资料
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">下载这个博客主题</a>
description: 学习使我快乐
creator: <a href="https://github.com/CoolestEnoch">@CoolestEnoch</a>

url: "https://github.com/CoolestEnoch/Course_SYU"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/CoolestEnoch'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: weibo_nickname
    github: CoolestEnoch
    #twitter: realDonaldTrump
    #gplus: 107108267983477358170
    #mail: mail@mail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
